id: P010349
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB16421
  title: རྨ་ལྷོའི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་ཡིག་བདམས་བསྒྲིགས། ༡
  author: ''
  volumes:
    be0593723ab2499e80c1b1ba8a3ccbb7:
      image_group_id: I1PD33767
      title: ''
      volume_number: 1
      total_pages: 62
      base_file: v001.txt
